const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const fmt = d => d ? new Date(d + 'T00:00:00').toLocaleDateString('pt-BR') : '-';
const isConfigured = () => SUPABASE_URL && SUPABASE_ANON_KEY && !SUPABASE_URL.includes('COLE_AQUI') && !SUPABASE_ANON_KEY.includes('COLE_AQUI');
let sb = null, user = null, profile = null, view = 'dashboard', editing = null, selectedLeader = '';
if (isConfigured()) sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

function ageKey(m){ if(!m.data_nascimento) return 9999; const now=new Date(); const b=new Date(m.data_nascimento+'T00:00:00'); let n=new Date(now.getFullYear(),b.getMonth(),b.getDate()); const today=new Date(now.getFullYear(),now.getMonth(),now.getDate()); if(n<today)n.setFullYear(now.getFullYear()+1); return Math.ceil((n-today)/86400000); }
async function init(){ if(!isConfigured()) return renderConfigWarning(); const {data:{session}} = await sb.auth.getSession(); user = session?.user || null; if(user) await loadProfile(); render(); }
async function loadProfile(){ let {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle(); if(!data){ const username=user.email || 'usuario'; await sb.from('profiles').insert({id:user.id,username:username,needs_change:false}); data={id:user.id,username:username,needs_change:false}; } profile=data; if(profile.needs_change) view='password'; }
function renderConfigWarning(){ $('#app').innerHTML=`<div class="login-wrap"><div class="login-card"><div class="logo-min">⚙️</div><h1>Configurar Supabase</h1><div class="setup-warning">Abra o arquivo <b>supabase-config.js</b> e cole a URL e a chave anon public do seu Supabase.</div><p>Depois crie as tabelas usando o arquivo <b>supabase_schema.sql</b>.</p></div></div>`; }
function render(){ if(!user) return renderLogin(); if(view==='password') return renderChangePass(); renderApp(); }
function renderLogin(){ $('#app').innerHTML=`<div class="login-wrap"><div class="login-card"><div class="logo-min">⛪</div><h1>Controle Ministerial</h1><div id="msg"></div><div class="field"><label>Email cadastrado no Supabase</label><input id="loginUser" type="email" placeholder="exemplo@email.com" autocomplete="username"></div><div class="field"><label>Senha</label><input id="loginPass" type="password" placeholder="Senha criada no Supabase" autocomplete="current-password"></div><button class="btn primary" onclick="doLogin()">Entrar no sistema</button><p class="small">Use o email e a senha criados em Authentication &gt; Users no Supabase.</p></div></div>`; }
async function doLogin(){ const email=$('#loginUser').value.trim().toLowerCase(), p=$('#loginPass').value; if(!email || !p) return $('#msg').innerHTML='<div class="error">Informe o email e a senha.</div>'; const {data,error}=await sb.auth.signInWithPassword({email:email,password:p}); if(error) return $('#msg').innerHTML='<div class="error">Email ou senha incorretos. Verifique se esse usuário existe em Authentication &gt; Users no Supabase.</div>'; user=data.user; await loadProfile(); render(); }
async function logout(){ await sb.auth.signOut(); user=null; profile=null; view='dashboard'; render(); }
function renderChangePass(){ $('#app').innerHTML=`<div class="login-wrap"><div class="login-card"><div class="logo-min">🔐</div><h1>Definir senha permanente</h1><p>Crie a senha definitiva para acessar de qualquer lugar.</p><div id="msg"></div><div class="field"><label>Nova senha</label><input id="p1" type="password"></div><div class="field"><label>Confirmar senha</label><input id="p2" type="password"></div><button class="btn primary" onclick="savePass()">Salvar senha</button></div></div>`; }
async function savePass(){ const p1=$('#p1').value,p2=$('#p2').value; if(p1.length<6||p1!==p2) return $('#msg').innerHTML='<div class="error">As senhas precisam ser iguais e ter no mínimo 6 caracteres.</div>'; const {error}=await sb.auth.updateUser({password:p1}); if(error) return $('#msg').innerHTML='<div class="error">Erro ao alterar senha.</div>'; await sb.from('profiles').update({needs_change:false}).eq('id',user.id); profile.needs_change=false; view='dashboard'; render(); }
function renderApp(){ $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="logo-min">⛪</div><div><h2>Marcos</h2><p>Controle Ministerial</p></div></div><div class="nav"><button class="btn ${view==='dashboard'?'active':''}" onclick="view='dashboard';renderDashboard()">📋 Membros</button><button class="btn ${view==='form'?'active':''}" onclick="editing=null;view='form';renderForm()">➕ Novo cadastro</button><button class="btn ${view==='leaders'?'active':''}" onclick="view='leaders';renderLeaders()">👥 Líderes</button><button class="btn" onclick="exportAllPDF()">📄 Exportar PDF</button><button class="btn" onclick="exportAllXLSX()">📊 Exportar Excel</button><button class="btn" onclick="logout()">🚪 Sair</button></div></aside><main class="main" id="main"></main></div>`; if(view==='form') renderForm(); else if(view==='leaders') renderLeaders(); else renderDashboard(); }
async function getMembers(){ const {data,error}=await sb.from('membros').select('*').order('nome',{ascending:true}); if(error){alert('Erro ao carregar membros: '+error.message); return []} return data||[]; }
async function renderDashboard(){ view='dashboard'; const data=await getMembers(); $('#main').innerHTML=`<div class="topbar"><div><h1>Painel de Membros</h1><p>Cadastro, acompanhamento de entrada/saída e relatórios da Recepção.</p></div><button class="btn primary" onclick="editing=null;view='form';renderForm()">Novo membro</button></div><div class="cards"><div class="stat"><p>Total</p><b>${data.length}</b></div><div class="stat green"><p>Ativos</p><b>${data.filter(m=>!m.data_saida).length}</b></div><div class="stat red"><p>Saíram</p><b>${data.filter(m=>m.data_saida).length}</b></div></div><div class="birthdays">${birthdayHTML(data)}</div><section class="panel"><div class="toolbar"><input id="q" placeholder="Buscar por nome, líder, contato ou endereço"><select id="status"><option value="todos">Todos</option><option value="ativos">Ativos</option><option value="sairam">Saíram</option></select><button class="btn" onclick="drawRows()">Filtrar</button></div><div id="rows"></div></section>`; drawRows(data); }
function birthdayHTML(data){ const month=new Date().getMonth(); const bmonth=data.filter(m=>m.data_nascimento&&new Date(m.data_nascimento+'T00:00:00').getMonth()===month).sort((a,b)=>new Date(a.data_nascimento)-new Date(b.data_nascimento)); const next=data.filter(m=>m.data_nascimento).sort((a,b)=>ageKey(a)-ageKey(b))[0]; return `<div class="birthday-card"><h3>🎂 Aniversariantes do mês</h3><p>${bmonth.length?bmonth.map(m=>`<b>${esc(m.nome)}</b> — ${fmt(m.data_nascimento)}`).join('<br>'):'Nenhum aniversariante cadastrado para este mês.'}</p></div><div class="birthday-card next"><h3>⭐ Próximo aniversário</h3><p>${next?`<b>${esc(next.nome)}</b><br>${fmt(next.data_nascimento)}<br><span class="small">Faltam ${ageKey(next)} dia(s)</span>`:'Nenhum membro com data de nascimento.'}</p></div>`; }
async function drawRows(prefetched){ const all=prefetched||await getMembers(); const q=($('#q')?.value||'').toLowerCase(), s=$('#status')?.value||'todos'; const data=all.filter(m=>(!q||[m.nome,m.contato,m.endereco,m.lider].join(' ').toLowerCase().includes(q))&&(s==='todos'||(s==='ativos'&&!m.data_saida)||(s==='sairam'&&m.data_saida))); $('#rows').innerHTML=table(data,true); }
function table(data,acts=false){ return `<div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>Contato</th><th>Nascimento</th><th>Líder</th><th>Entrada</th><th>Saída</th><th>Status</th>${acts?'<th>Ações</th>':''}</tr></thead><tbody>${data.map(m=>`<tr><td><b>${esc(m.nome)}</b><br><span class="small">${esc(m.endereco||'')}</span></td><td>${esc(m.contato||'')}</td><td>${fmt(m.data_nascimento)}</td><td>${esc(m.lider||'-')}</td><td>${fmt(m.data_entrada)}</td><td>${fmt(m.data_saida)}</td><td><span class="badge ${m.data_saida?'off':'ok'}">${m.data_saida?'Saiu':'Ativo'}</span></td>${acts?`<td class="actions"><button class="btn" onclick="editMember('${m.id}')">Editar</button><button class="btn" onclick='exportPDF([${JSON.stringify(m)}],"membro_${esc(m.nome)}")'>PDF</button><button class="btn" onclick='exportXLSX([${JSON.stringify(m)}],"membro_${esc(m.nome)}")'>Excel</button><button class="btn red" onclick="delMember('${m.id}')">Excluir</button></td>`:''}</tr>`).join('')||'<tr><td colspan="8">Nenhum membro encontrado.</td></tr>'}</tbody></table></div>`; }
async function editMember(id){ const {data}=await sb.from('membros').select('*').eq('id',id).single(); editing=data; view='form'; renderForm(); }
async function delMember(id){ if(!confirm('Excluir este cadastro?')) return; await sb.from('membros').delete().eq('id',id); renderDashboard(); }
function renderForm(){ const m=editing||{}; $('#main').innerHTML=`<div class="topbar"><div><h1>Novo membro</h1><p>Preencha os dados da Recepção com organização.</p></div><button class="btn" onclick="view='dashboard';renderDashboard()">← Voltar</button></div><section class="panel"><div class="form-grid"><div class="field"><label>Nome completo *</label><input id="nome" value="${esc(m.nome||'')}"></div><div class="field"><label>Número para contato</label><input id="contato" value="${esc(m.contato||'')}"></div><div class="field"><label>Data de nascimento</label><input id="nascimento" type="date" value="${esc(m.data_nascimento||'')}"></div><div class="field"><label>Nome do líder</label><input id="lider" value="${esc(m.lider||'')}"></div><div class="field full"><label>Endereço</label><input id="endereco" value="${esc(m.endereco||'')}"></div><div class="field"><label>Data de entrada na recepção *</label><input id="entrada" type="date" value="${esc(m.data_entrada||'')}"></div><div class="field"><label>Data de saída da recepção</label><input id="saida" type="date" value="${esc(m.data_saida||'')}"></div><div class="field full"><label>Observações</label><textarea id="obs" rows="5">${esc(m.observacoes||'')}</textarea></div></div><button class="btn primary" onclick="saveMember()">Salvar cadastro</button></section>`; }
async function saveMember(){ const item={user_id:user.id,nome:$('#nome').value.trim(),contato:$('#contato').value.trim(),data_nascimento:$('#nascimento').value||null,lider:$('#lider').value.trim(),endereco:$('#endereco').value.trim(),data_entrada:$('#entrada').value||null,data_saida:$('#saida').value||null,observacoes:$('#obs').value.trim()}; if(!item.nome||!item.data_entrada) return alert('Preencha nome e data de entrada.'); let res; if(editing?.id) res=await sb.from('membros').update(item).eq('id',editing.id); else res=await sb.from('membros').insert(item); if(res.error) return alert('Erro ao salvar: '+res.error.message); editing=null; view='dashboard'; renderDashboard(); }
async function renderLeaders(){ view='leaders'; const data=await getMembers(); const leaders=[...new Set(data.map(m=>m.lider).filter(Boolean))].sort(); selectedLeader=selectedLeader||leaders[0]||''; const group=data.filter(m=>m.lider===selectedLeader); $('#main').innerHTML=`<div class="topbar"><div><h1>Líderes</h1><p>Visualize os membros vinculados a cada líder.</p></div></div><div class="leaders-grid"><section class="panel"><h3>Nomes dos líderes</h3><br><div class="leader-list">${leaders.map(l=>`<button class="leader-item ${l===selectedLeader?'active':''}" onclick="selectedLeader='${esc(l)}';renderLeaders()">${esc(l)} <span class="small">(${data.filter(m=>m.lider===l).length})</span></button>`).join('')||'<p>Nenhum líder cadastrado.</p>'}</div></section><section class="panel"><h3>${esc(selectedLeader||'Selecione um líder')}</h3><p class="small">Membros vinculados</p><div class="actions"><button class="btn" onclick="exportLeaderPDF()">PDF deste líder</button><button class="btn" onclick="exportLeaderXLSX()">Excel deste líder</button></div><br>${table(group,false)}</section></div>`; }
function rows(data){ return data.map(m=>({'Nome do membro':m.nome,'Número para contato':m.contato,'Data de nascimento':fmt(m.data_nascimento),'Nome do líder':m.lider,'Data de entrada':fmt(m.data_entrada),'Data de saída':fmt(m.data_saida),'Endereço':m.endereco,'Observações':m.observacoes,'Status':m.data_saida?'Saiu':'Ativo'})); }
function exportXLSX(data,name='controle_ministerial_recepcao'){ const wb=XLSX.utils.book_new(), ws=XLSX.utils.json_to_sheet(rows(data)); XLSX.utils.book_append_sheet(wb,ws,'Membros'); XLSX.writeFile(wb,`${name}.xlsx`); }
async function exportAllXLSX(){ exportXLSX(await getMembers(),'todos_membros_recepcao'); }
async function exportLeaderXLSX(){ const data=(await getMembers()).filter(m=>m.lider===selectedLeader); exportXLSX(data,`lider_${selectedLeader}`); }
function exportPDF(data,name='controle_ministerial_recepcao'){ const {jsPDF}=window.jspdf; const doc=new jsPDF({orientation:'landscape'}); doc.setFontSize(18); doc.text('Controle Ministerial - Recepção',14,16); doc.setFontSize(11); doc.text(`Relatório gerado em ${new Date().toLocaleDateString('pt-BR')}`,14,24); const r=rows(data); doc.autoTable({startY:30,head:[Object.keys(r[0]||{'Nome do membro':'','Número para contato':'','Data de nascimento':'','Nome do líder':'','Data de entrada':'','Data de saída':'','Status':''})],body:r.map(Object.values),styles:{fontSize:8,cellPadding:2},headStyles:{fillColor:[37,99,235]},alternateRowStyles:{fillColor:[239,246,255]}}); doc.save(`${name}.pdf`); }
async function exportAllPDF(){ exportPDF(await getMembers(),'todos_membros_recepcao'); }
async function exportLeaderPDF(){ const data=(await getMembers()).filter(m=>m.lider===selectedLeader); exportPDF(data,`lider_${selectedLeader}`); }
init();
