// COLE AQUI OS DADOS DO SEU PROJETO SUPABASE
// Caminho: Supabase > Project Settings > API
const SUPABASE_URL = "COLE_AQUI_A_URL_DO_SUPABASE";
const SUPABASE_ANON_KEY = "COLE_AQUI_A_CHAVE_ANON_PUBLIC";
